create extension if not exists "pgcrypto";

create table if not exists tags (
  id uuid primary key default gen_random_uuid(),
  tag_id text not null unique,
  activation_code text,
  activation_code_hash text,
  batch_id text,
  owner_user_id uuid,
  owner_email text,
  status text not null default 'unactivated' check (status in ('unactivated', 'active', 'lost', 'disabled')),
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists pets (
  id uuid primary key default gen_random_uuid(),
  tag_id text not null unique references tags(tag_id) on delete cascade,
  owner_user_id uuid,
  owner_email text not null,
  name text not null default 'My Pet',
  photo_url text,
  breed text,
  age text,
  sex text,
  address text,
  about text,
  contact_name_1 text,
  contact_phone_1 text,
  contact_name_2 text,
  contact_phone_2 text,
  contact_email text,
  show_phone boolean not null default true,
  show_address boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists scan_events (
  id uuid primary key default gen_random_uuid(),
  tag_id text not null references tags(tag_id) on delete cascade,
  pet_id uuid references pets(id) on delete set null,
  scanned_at timestamptz not null default now(),
  latitude double precision,
  longitude double precision,
  map_url text,
  ip_address text,
  ip_hash text,
  user_agent text,
  location_permission text,
  notification_status text,
  created_at timestamptz not null default now()
);

create table if not exists activation_attempts (
  id bigint generated by default as identity primary key,
  tag_id text,
  ip_hash text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create table if not exists profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  terms_accepted_at timestamptz,
  terms_version text,
  privacy_accepted_at timestamptz,
  privacy_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

alter table tags add column if not exists owner_user_id uuid;
alter table pets add column if not exists owner_user_id uuid;
alter table tags add column if not exists activation_code_hash text;
alter table tags add column if not exists batch_id text;
alter table scan_events add column if not exists ip_hash text;
alter table profiles add column if not exists terms_accepted_at timestamptz;
alter table profiles add column if not exists terms_version text;
alter table profiles add column if not exists privacy_accepted_at timestamptz;
alter table profiles add column if not exists privacy_version text;
alter table tags alter column activation_code drop not null;

update tags
set activation_code_hash = encode(digest(upper(trim(activation_code)), 'sha256'), 'hex')
where activation_code is not null and activation_code_hash is null;

update tags set activation_code = null where activation_code_hash is not null;

create index if not exists tags_owner_user_id_idx on tags(owner_user_id);
create index if not exists pets_owner_user_id_idx on pets(owner_user_id);
create index if not exists tags_status_created_at_idx on tags(status, created_at desc);
create index if not exists tags_batch_id_idx on tags(batch_id);
create index if not exists scan_events_tag_scanned_at_idx on scan_events(tag_id, scanned_at desc);
create index if not exists scan_events_scanned_at_idx on scan_events(scanned_at desc);
create index if not exists scan_events_ip_scanned_at_idx on scan_events(ip_hash, scanned_at desc);
create index if not exists scan_events_dedupe_idx on scan_events(tag_id, ip_hash, scanned_at desc);
create index if not exists activation_attempts_ip_time_idx on activation_attempts(ip_hash, attempted_at desc);
create index if not exists activation_attempts_time_idx on activation_attempts(attempted_at);
create index if not exists profiles_email_idx on profiles(lower(email));
create index if not exists profiles_created_at_idx on profiles(created_at desc);
create index if not exists admin_audit_logs_time_idx on admin_audit_logs(created_at desc);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (
    user_id, email, terms_accepted_at, terms_version, privacy_accepted_at, privacy_version
  ) values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'terms_accepted_at', '')::timestamptz,
    new.raw_user_meta_data ->> 'terms_version',
    nullif(new.raw_user_meta_data ->> 'privacy_accepted_at', '')::timestamptz,
    new.raw_user_meta_data ->> 'privacy_version'
  )
  on conflict (user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute procedure public.handle_new_auth_user();

insert into profiles (user_id, email, created_at)
select id, coalesce(email, ''), created_at from auth.users
on conflict (user_id) do update set email = excluded.email, updated_at = now();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('pet-photos', 'pet-photos', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table tags enable row level security;
alter table pets enable row level security;
alter table scan_events enable row level security;
alter table activation_attempts enable row level security;
alter table profiles enable row level security;
alter table admin_users enable row level security;
alter table admin_audit_logs enable row level security;
alter table site_settings enable row level security;

drop policy if exists "public read active tags" on tags;
drop policy if exists "public read pets" on pets;
drop policy if exists "public create scan events" on scan_events;
